### ISSUE TITLE
Rubygems

### ISSUE THREAD

**Issue by jankeesvw** [hauleth/vanilla-ujs#15]
Would be great if this Gem was also available on Rubygems. 

Right now @Ximik, who owns a fork, released a gem with this name, was a little bit confusing to me: https://rubygems.org/gems/vanilla-ujs/.

**Comment by Ximik** [comment]
Sorry, my bad. Forgot to add @hauleth as owner.

**Comment by hauleth** [comment]
@Ximik is now part of the repo management. Yay!

**Comment by Ximik** [comment]
@jankeesvw you can use this gem from rubygems now. Just

> gem 'vanilla-ujs'

in your Gemfile

**Comment by jankeesvw** [comment]
Great work! Thanks..
