### ISSUE TITLE
Wiki / readme

### ISSUE THREAD

**Issue by miks** [hauleth/vanilla-ujs#23]
Is there any readme available how to use this gem?
I tried to replace with jquery-ujs with vanilla-ujs, but it's not working just by changing gems.
For example, in jquery-ujs there is "ajax:beforeSend" but in vanilla-ujs there is no such event.

**Comment by walterdavis** [comment]
It's not a perfect drop-in replacement at the moment, more of an 80% solution (will work perfectly with a scaffolded Rails app, for example). How about adding this listener, and submitting a PR?

**Comment by miks** [comment]
Is there any objective for this gem to be drop-in replacement? If yes, I can make PR for "ajax:beforeSend".

**Comment by miks** [comment]
And what about documentation? Is it better to add some description in readme or put all information in github wiki?

**Comment by walterdavis** [comment]
DHH mentioned it recently, and wondered aloud if it would be a good fit for Rails 5.x. So yes, there is such an objective.

Walter

**Comment by hauleth** [comment]
@miks yes, of course it is thought as "almost" drop in replacement. Not everything is possible only via vanilla JS, but as much as is possible we should provide.
