### ISSUE TITLE
Throw this on NPM?

### ISSUE THREAD

**Issue by greypants** [hauleth/vanilla-ujs#4]
Thanks for creating this! I'm replacing the asset pipeline with gulp tasks. It'd be sweet if I could list this in dependencies in package.json

**Comment by hauleth** [comment]
https://www.npmjs.com/package/vanilla-ujs

**Comment by scarfacedeb** [comment]
@hauleth I noticed that npm has rather old vanilla-ujs version. Are you planning to keep it up to date?

**Comment by hauleth** [comment]
I do not have idea how to do it in way that it could be RubyGem and NPM package at once. I will try after the weekend.

**Comment by scarfacedeb** [comment]
@hauleth In theory, you can do the same thing as actioncable:
https://github.com/rails/rails/blob/master/actioncable/README.md#frontend-assets

**Comment by hauleth** [comment]
@scarfacedeb I could, but there is no point as ActionCable JS doesn't have any dependencies, so VanillaJS implementation would not provide any gain.

**Comment by mhuggins** [comment]
The gain is not for VanillaJS itself, but for users of VanillaJS that rely on a package manager.

**Comment by hauleth** [comment]
@mhuggins I have updated NPM. If you could try if it works.
